### ISSUE TITLE
Plotting Error When Using Jupyter Environment

### ISSUE THREAD

**Issue by jcforaker** [sportsdataverse/sportyR#28] opened 2023-07-19 21:41 UTC
Hello, and thanks for writing this excellent package.  I have no issues getting the plotting to work when I use the package in R Studio.  I want to use R with a Jupyter environment, and I was able to install the package.  However, I get the following error when I run the code below:

library(sportyR)
geom_baseball(league = "MLB")

ERROR while rich displaying an object: Error: Aesthetics must be either length 1 or the same as the data (2000): group

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_text.default(obj)
9. paste(capture.output(print(obj)), collapse = "\n")
10. capture.output(print(obj))
11. evalVis(expr)
12. withVisible(eval(expr, pf))
13. eval(expr, pf)
14. eval(expr, pf)
15. print(obj)
16. print.ggplot(obj)
17. ggplot_build(x)
18. ggplot_build.ggplot(x)
19. by_layer(function(l, d) l$compute_aesthetics(d, plot))
20. f(l = layers[[i]], d = data[[i]])
21. l$compute_aesthetics(d, plot)
22. f(..., self = self)
23. check_aesthetics(evaled, n)
24. stop("Aesthetics must be either length 1 or the same as the data (", 
  .     n, "): ", paste(names(which(!good)), collapse = ", "), call. = FALSE)

I would appreciate any insight you can provide regarding how to address this issue.

**Comment by rossdrucker** [comment] 2023-07-19 22:57
Hey @jcforaker, glad you're enjoying the package!

Unfortunately, I'm not sure that I'm able to help with this as I don't think that this has anything to do with `{sportyR}`. I'm unable to reproduce your issue on my end:

<img width="1152" alt="Screen Shot 2023-07-19 at 5 51 03 PM" src="https://github.com/sportsdataverse/sportyR/assets/15791518/312df5fd-0d9d-412f-8b97-4e94460a0a07">

Just in a bit of research, perhaps you need to run the following code first?

```r
install.packages("IRkernel")
IRkernel::installspec(user = FALSE)
```

Happy to continue researching, but I don't know that I can help resolve without being able to recreate it. For reference, I'm using `IRkernel v1.3.2` and the following from `jupyter --version`:

```
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : 5.1.1
ipython          : 7.26.0
ipykernel        : 6.2.0
jupyter client   : 6.1.12
jupyter lab      : 3.1.8
nbconvert        : 6.1.0
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by jcforaker** [comment] 2023-07-19 23:36
I appreciate the quick reply.  I tried to do what you said, but it didn't seem to help.  I will try installing the package on a different machine and see if I have any better luck.  FWIW, here are my versions:

jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5

**Comment by rossdrucker** [comment] 2023-07-19 23:52
Can you share the results of `sessioninfo::session_info()`?

**Comment by jcforaker** [comment] 2023-07-20 00:17
Thanks for your continued support.  Here are the results of sessioninfo::session_info()

- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RTerm                       
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2023-07-19                  

- Packages -------------------------------------------------------------------
 ! package     * version date       lib source        
   assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 D backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
   base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.6.0)
   broom         0.5.2   2019-04-07 [1] CRAN (R 3.6.0)
   cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
 V cli           1.1.0   2021-04-26 [1] CRAN (R 3.6.3)
 D colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
   crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
   digest        0.6.18  2018-10-10 [1] CRAN (R 3.6.0)
 D dplyr       * 0.8.0.1 2019-02-15 [1] CRAN (R 3.6.0)
   evaluate      0.13    2019-02-12 [1] CRAN (R 3.6.0)
   forcats     * 0.4.0   2019-02-17 [1] CRAN (R 3.6.0)
   generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.0)
   ggplot2     * 3.1.1   2019-04-07 [1] CRAN (R 3.6.0)
 D glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
   gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
 D haven         2.1.0   2019-02-19 [1] CRAN (R 3.6.0)
   hms           0.4.2   2018-03-10 [1] CRAN (R 3.6.0)
   htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
   httr          1.4.0   2018-12-11 [1] CRAN (R 3.6.0)
   IRdisplay     0.7.0   2018-11-29 [1] CRAN (R 3.6.0)
   IRkernel      0.8.15  2019-05-16 [1] local         
   jsonlite      1.6     2018-12-07 [1] CRAN (R 3.6.0)
   lattice       0.20-38 2018-11-04 [1] CRAN (R 3.6.0)
   lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
 D lubridate     1.7.4   2018-04-11 [1] CRAN (R 3.6.0)
 D magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
   modelr        0.1.4   2019-02-18 [1] CRAN (R 3.6.0)
   munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
 D nlme          3.1-139 2019-04-09 [1] CRAN (R 3.6.0)
   pbdZMQ        0.3-3   2018-05-05 [1] CRAN (R 3.6.0)
   pillar        1.3.1   2018-12-15 [1] CRAN (R 3.6.0)
   pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.6.0)
   plyr          1.8.4   2016-06-08 [1] CRAN (R 3.6.0)
 D purrr       * 0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
   R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
   Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.6.0)
 D readr       * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
 D readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.0)
   repr          0.19.2  2019-02-06 [1] CRAN (R 3.6.0)
 D rlang         0.3.4   2019-04-07 [1] CRAN (R 3.6.0)
   rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
   rvest         0.3.3   2019-04-11 [1] CRAN (R 3.6.0)
   scales        1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
   sessioninfo * 1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
   sportyR     * 2.2.1   2023-06-15 [1] CRAN (R 3.6.1)
 D stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
   stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
 D tibble      * 2.1.1   2019-03-16 [1] CRAN (R 3.6.0)
 D tidyr       * 0.8.3   2019-03-01 [1] CRAN (R 3.6.0)
   tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
   tidyverse   * 1.2.1   2017-11-14 [1] CRAN (R 3.6.0)
   uuid          0.1-2   2015-07-28 [1] CRAN (R 3.6.0)
   withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 D xml2          1.2.0   2018-01-24 [1] CRAN (R 3.6.0)

[1] C:/ProgramData/Anaconda3/Lib/R/library

 V -- Loaded and on-disk version mismatch.
 D -- DLL MD5 mismatch, broken installation.

**Comment by rossdrucker** [comment] 2023-07-20 03:24
It looks like you've got some packages that are out of date and/or that have broken installs. Try restarting R and upgrading/clean reinstalling these packages

**Comment by rossdrucker** [comment] 2023-07-25 17:44
@jcforaker just checking back in on this? If that resolved your issue, I'm going to close.... Still don't believe this is something related to `{sportyR}` in particular

**Comment by jcforaker** [comment] 2023-07-25 20:02
Sir,    Please feel free to mark the issue as resolved.  What you suggested didn’t fix it on my machine, but I think it is a bug on my end.  I don’t think the issue is related to {sportyR}.  Thanks again for the attempt to help me fix my issue.V/r,Joseph ForakerOn Jul 25, 2023, at 13:44, Ross Drucker ***@***.***> wrote:﻿
@jcforaker just checking back in on this? If that resolved your issue, I'm going to close.... Still don't believe this is something related to {sportyR} in particular

**Comment by rossdrucker** [comment] 2023-07-25 20:39
Closing per above discussion; issue does not pertaining to `{sportyR}`

**Closed by rossdrucker** 2023-07-25 20:39 UTC
